# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

env:
  MYSQL_VERSION: 5.6.36
  MONGO_VERSION: 3.2.16
  DOCKER_IMAGE: abstract2tech/edxbackup

jobs:
  build-n-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest docker-compose
        pip install -r ./egg/requirements.txt
        pip install ./egg
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with pytest
      run: |
        pytest
    - name: Build image
      run: |
        docker build . -t $DOCKER_IMAGE:${{ github.sha }}
        echo $DOCKER_IMAGE:${{ github.sha }} > build-image
    - name: Test dump
      run: |
        make test-dump
    - name: Test restore
      run: |
        make test-restore
